### ISSUE TITLE
Issue with log in

### ISSUE THREAD

**Issue by keith-quirk** [Peach-Cake/CoView#26]
`if($row["UserType"]=="Patient"){
    $sqlMan = "SELECT UserID FROM Patient
    WHERE UserID = '$id';";
    $resultMan = $conn->query($sqlMan);
    $rowMan = mysqli_fetch_assoc($resultMan);
    $_SESSION["Username"] = $rowMan["Username"];
    $_SESSION["LoggedIn"] = $user;
    echo "Patient";
    exit;
  }`

**Comment by b1700161** [comment]
Solved on wednesday

**Comment by ashburger** [comment]
Solved on Wednesday
